version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["deno", "run", "--allow-net", "--allow-env", "--allow-read", "--allow-write", "--import-map=src/import_map.json","src/server.ts"]
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/deno_crud

  mongo:
    image: mongo:latest
    container_name: deno_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
